CREATE TABLE IF NOT EXISTS `articlesblog` (
  IDARTICULO INT AUTO_INCREMENT,
  TITLE varchar(255),
  IMAGE varchar(255),
  DESCRIPTION varchar(255),
  CONTENT text,
  KEYWORDS varchar(255),
  AUTOR varchar(255),
  DATE TIMESTAMP,

   PRIMARY KEY (IDARTICULO),
   UNIQUE (TITLE)
)
